POST {{ip_deploy}}/api/login
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

> {% client.global.set("auth_token", response.body.access_token); %}

###
GET {{ip_deploy}}/api/follow/2
Authorization: Bearer {{auth_token}}

###
GET {{ip_deploy}}/api/followings/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###
GET {{ip_deploy}}/api/followers/2
Authorization: Bearer {{auth_token}}
Content-Type: application/json
